[build]
  base = "Emanam - Sentiment analysis SE 1.0 (AG)/client"
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
